import type { Candidate, Job } from './db/types';

export const seedCandidates: Candidate[] = [];

export const seedJobs: Job[] = [
  {
    id: 'job-1',
    title: 'Senior Frontend Developer',
    description: 'Build modern, responsive web applications using React and TypeScript. Lead frontend architecture decisions and mentor junior developers.',
    mustHaveSkills: ['react', 'typescript', 'next.js'],
    niceToHaveSkills: ['tailwind', 'graphql', 'docker'],
    minYears: 5,
    location: 'San Francisco, CA',
    isActive: true,
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 86400000,
  },
  {
    id: 'job-2',
    title: 'Full Stack Engineer',
    description: 'Develop and maintain web applications using modern JavaScript frameworks. Work on both frontend and backend systems.',
    mustHaveSkills: ['javascript', 'node', 'react'],
    niceToHaveSkills: ['typescript', 'postgresql', 'aws'],
    minYears: 3,
    location: 'Remote',
    isActive: true,
    createdAt: Date.now() - 172800000,
    updatedAt: Date.now() - 172800000,
  },
  {
    id: 'job-3',
    title: 'Backend Developer - Python',
    description: 'Design and implement scalable backend services using Python and Django. Experience with microservices architecture required.',
    mustHaveSkills: ['python', 'django', 'postgresql'],
    niceToHaveSkills: ['redis', 'docker', 'kubernetes'],
    minYears: 4,
    location: 'New York, NY',
    isActive: true,
    createdAt: Date.now() - 259200000,
    updatedAt: Date.now() - 259200000,
  },
  {
    id: 'job-4',
    title: 'Mobile Developer - React Native',
    description: 'Build cross-platform mobile applications for iOS and Android. Collaborate with design team to implement pixel-perfect UIs.',
    mustHaveSkills: ['react', 'react native', 'javascript'],
    niceToHaveSkills: ['typescript', 'graphql', 'firebase'],
    minYears: 3,
    location: 'Austin, TX',
    isActive: true,
    createdAt: Date.now() - 345600000,
    updatedAt: Date.now() - 345600000,
  },
  {
    id: 'job-5',
    title: 'DevOps Engineer',
    description: 'Manage cloud infrastructure and CI/CD pipelines. Implement automation and monitoring solutions for production systems.',
    mustHaveSkills: ['aws', 'docker', 'kubernetes'],
    niceToHaveSkills: ['terraform', 'jenkins', 'python'],
    minYears: 4,
    location: 'Seattle, WA',
    isActive: true,
    createdAt: Date.now() - 432000000,
    updatedAt: Date.now() - 432000000,
  },
  {
    id: 'job-6',
    title: 'UI/UX Designer',
    description: 'Create beautiful and intuitive user interfaces. Conduct user research and usability testing to inform design decisions.',
    mustHaveSkills: ['figma', 'ui design', 'user research'],
    niceToHaveSkills: ['html', 'css', 'javascript'],
    minYears: 3,
    location: 'Los Angeles, CA',
    isActive: true,
    createdAt: Date.now() - 518400000,
    updatedAt: Date.now() - 518400000,
  },
  {
    id: 'job-7',
    title: 'Data Engineer',
    description: 'Build and maintain data pipelines. Work with large-scale data processing systems and optimize database performance.',
    mustHaveSkills: ['python', 'sql', 'data engineering'],
    niceToHaveSkills: ['spark', 'airflow', 'aws'],
    minYears: 3,
    location: 'Chicago, IL',
    isActive: true,
    createdAt: Date.now() - 604800000,
    updatedAt: Date.now() - 604800000,
  },
  {
    id: 'job-8',
    title: 'Machine Learning Engineer',
    description: 'Develop and deploy ML models for production systems. Experience with deep learning frameworks and model optimization.',
    mustHaveSkills: ['python', 'machine learning', 'tensorflow'],
    niceToHaveSkills: ['pytorch', 'kubernetes', 'aws'],
    minYears: 4,
    location: 'Boston, MA',
    isActive: true,
    createdAt: Date.now() - 691200000,
    updatedAt: Date.now() - 691200000,
  },
  {
    id: 'job-9',
    title: 'iOS Developer',
    description: 'Build native iOS applications using Swift. Focus on performance, smooth animations, and delightful user experiences.',
    mustHaveSkills: ['swift', 'ios', 'xcode'],
    niceToHaveSkills: ['swiftui', 'core data', 'combine'],
    minYears: 3,
    location: 'San Diego, CA',
    isActive: true,
    createdAt: Date.now() - 777600000,
    updatedAt: Date.now() - 777600000,
  },
  {
    id: 'job-10',
    title: 'Android Developer',
    description: 'Develop high-quality Android applications using Kotlin. Implement Material Design and modern Android architecture patterns.',
    mustHaveSkills: ['kotlin', 'android', 'java'],
    niceToHaveSkills: ['jetpack compose', 'mvvm', 'room'],
    minYears: 3,
    location: 'Denver, CO',
    isActive: true,
    createdAt: Date.now() - 864000000,
    updatedAt: Date.now() - 864000000,
  },
  {
    id: 'job-11',
    title: 'QA Automation Engineer',
    description: 'Design and implement automated testing frameworks. Write comprehensive test suites for web and mobile applications.',
    mustHaveSkills: ['selenium', 'cypress', 'javascript'],
    niceToHaveSkills: ['pytest', 'jenkins', 'docker'],
    minYears: 2,
    location: 'Portland, OR',
    isActive: true,
    createdAt: Date.now() - 950400000,
    updatedAt: Date.now() - 950400000,
  },
  {
    id: 'job-12',
    title: 'Security Engineer',
    description: 'Implement security best practices and conduct vulnerability assessments. Respond to security incidents and maintain compliance.',
    mustHaveSkills: ['security', 'penetration testing', 'networking'],
    niceToHaveSkills: ['python', 'aws', 'kubernetes'],
    minYears: 5,
    location: 'Washington, DC',
    isActive: true,
    createdAt: Date.now() - 1036800000,
    updatedAt: Date.now() - 1036800000,
  },
  {
    id: 'job-13',
    title: 'Product Manager',
    description: 'Define product roadmap and prioritize features. Work closely with engineering and design teams to deliver customer value.',
    mustHaveSkills: ['product management', 'agile', 'user research'],
    niceToHaveSkills: ['sql', 'analytics', 'figma'],
    minYears: 4,
    location: 'San Francisco, CA',
    isActive: true,
    createdAt: Date.now() - 1123200000,
    updatedAt: Date.now() - 1123200000,
  },
  {
    id: 'job-14',
    title: 'Backend Engineer - Node.js',
    description: 'Build scalable REST APIs and microservices. Optimize database queries and implement caching strategies.',
    mustHaveSkills: ['node', 'javascript', 'postgresql'],
    niceToHaveSkills: ['typescript', 'redis', 'graphql'],
    minYears: 3,
    location: 'Austin, TX',
    isActive: true,
    createdAt: Date.now() - 1209600000,
    updatedAt: Date.now() - 1209600000,
  },
  {
    id: 'job-15',
    title: 'Frontend Developer - Vue.js',
    description: 'Create responsive web applications using Vue.js. Implement state management and routing for complex SPAs.',
    mustHaveSkills: ['vue', 'javascript', 'html'],
    niceToHaveSkills: ['typescript', 'nuxt', 'tailwind'],
    minYears: 2,
    location: 'Remote',
    isActive: true,
    createdAt: Date.now() - 1296000000,
    updatedAt: Date.now() - 1296000000,
  },
  {
    id: 'job-16',
    title: 'Cloud Architect',
    description: 'Design cloud infrastructure solutions on AWS. Implement serverless architectures and ensure high availability.',
    mustHaveSkills: ['aws', 'cloud architecture', 'terraform'],
    niceToHaveSkills: ['kubernetes', 'docker', 'python'],
    minYears: 6,
    location: 'Seattle, WA',
    isActive: true,
    createdAt: Date.now() - 1382400000,
    updatedAt: Date.now() - 1382400000,
  },
  {
    id: 'job-17',
    title: 'Data Scientist',
    description: 'Analyze large datasets and build predictive models. Communicate insights to stakeholders and drive data-driven decisions.',
    mustHaveSkills: ['python', 'machine learning', 'sql'],
    niceToHaveSkills: ['r', 'tableau', 'spark'],
    minYears: 3,
    location: 'New York, NY',
    isActive: true,
    createdAt: Date.now() - 1468800000,
    updatedAt: Date.now() - 1468800000,
  },
  {
    id: 'job-18',
    title: 'Site Reliability Engineer',
    description: 'Ensure system reliability and performance at scale. Implement monitoring, alerting, and incident response procedures.',
    mustHaveSkills: ['linux', 'python', 'monitoring'],
    niceToHaveSkills: ['kubernetes', 'prometheus', 'grafana'],
    minYears: 4,
    location: 'San Francisco, CA',
    isActive: true,
    createdAt: Date.now() - 1555200000,
    updatedAt: Date.now() - 1555200000,
  },
  {
    id: 'job-19',
    title: 'Game Developer - Unity',
    description: 'Create engaging mobile and desktop games. Implement game mechanics, physics, and multiplayer features.',
    mustHaveSkills: ['unity', 'c#', 'game development'],
    niceToHaveSkills: ['3d modeling', 'shader programming', 'multiplayer'],
    minYears: 3,
    location: 'Los Angeles, CA',
    isActive: true,
    createdAt: Date.now() - 1641600000,
    updatedAt: Date.now() - 1641600000,
  },
  {
    id: 'job-20',
    title: 'Blockchain Developer',
    description: 'Develop smart contracts and decentralized applications. Experience with Ethereum and Solidity required.',
    mustHaveSkills: ['solidity', 'blockchain', 'ethereum'],
    niceToHaveSkills: ['web3', 'javascript', 'rust'],
    minYears: 2,
    location: 'Remote',
    isActive: true,
    createdAt: Date.now() - 1728000000,
    updatedAt: Date.now() - 1728000000,
  },
  {
    id: 'job-21',
    title: 'Technical Writer',
    description: 'Create comprehensive documentation for APIs and SDKs. Write tutorials, guides, and reference materials.',
    mustHaveSkills: ['technical writing', 'documentation', 'communication'],
    niceToHaveSkills: ['markdown', 'git', 'api'],
    minYears: 2,
    location: 'Remote',
    isActive: true,
    createdAt: Date.now() - 1814400000,
    updatedAt: Date.now() - 1814400000,
  },
  {
    id: 'job-22',
    title: 'Database Administrator',
    description: 'Manage and optimize database systems. Ensure data integrity, security, and implement backup strategies.',
    mustHaveSkills: ['postgresql', 'sql', 'database'],
    niceToHaveSkills: ['mysql', 'mongodb', 'redis'],
    minYears: 4,
    location: 'Chicago, IL',
    isActive: true,
    createdAt: Date.now() - 1900800000,
    updatedAt: Date.now() - 1900800000,
  },
  {
    id: 'job-23',
    title: 'Scrum Master',
    description: 'Facilitate agile ceremonies and remove blockers. Coach team on agile practices and continuous improvement.',
    mustHaveSkills: ['scrum', 'agile', 'project management'],
    niceToHaveSkills: ['jira', 'confluence', 'coaching'],
    minYears: 3,
    location: 'Boston, MA',
    isActive: true,
    createdAt: Date.now() - 1987200000,
    updatedAt: Date.now() - 1987200000,
  },
  {
    id: 'job-24',
    title: 'Systems Administrator',
    description: 'Maintain and troubleshoot server infrastructure. Manage user accounts, permissions, and system updates.',
    mustHaveSkills: ['linux', 'networking', 'bash'],
    niceToHaveSkills: ['ansible', 'python', 'monitoring'],
    minYears: 3,
    location: 'Dallas, TX',
    isActive: true,
    createdAt: Date.now() - 2073600000,
    updatedAt: Date.now() - 2073600000,
  },
  {
    id: 'job-25',
    title: 'Frontend Developer - Angular',
    description: 'Build enterprise web applications using Angular. Implement complex forms and data-driven interfaces.',
    mustHaveSkills: ['angular', 'typescript', 'rxjs'],
    niceToHaveSkills: ['ngrx', 'material design', 'jest'],
    minYears: 3,
    location: 'Atlanta, GA',
    isActive: true,
    createdAt: Date.now() - 2160000000,
    updatedAt: Date.now() - 2160000000,
  },
  {
    id: 'job-26',
    title: 'Backend Developer - Java',
    description: 'Develop enterprise applications using Java and Spring Boot. Design and implement RESTful services.',
    mustHaveSkills: ['java', 'spring', 'sql'],
    niceToHaveSkills: ['microservices', 'kafka', 'docker'],
    minYears: 4,
    location: 'Minneapolis, MN',
    isActive: true,
    createdAt: Date.now() - 2246400000,
    updatedAt: Date.now() - 2246400000,
  },
  {
    id: 'job-27',
    title: 'Infrastructure Engineer',
    description: 'Design and maintain scalable infrastructure. Automate deployment processes and ensure system reliability.',
    mustHaveSkills: ['terraform', 'aws', 'linux'],
    niceToHaveSkills: ['ansible', 'python', 'kubernetes'],
    minYears: 4,
    location: 'Phoenix, AZ',
    isActive: true,
    createdAt: Date.now() - 2332800000,
    updatedAt: Date.now() - 2332800000,
  },
  {
    id: 'job-28',
    title: 'Backend Developer - Go',
    description: 'Build high-performance backend services using Go. Optimize for concurrency and low latency.',
    mustHaveSkills: ['go', 'golang', 'microservices'],
    niceToHaveSkills: ['grpc', 'kubernetes', 'postgresql'],
    minYears: 3,
    location: 'San Francisco, CA',
    isActive: true,
    createdAt: Date.now() - 2419200000,
    updatedAt: Date.now() - 2419200000,
  },
  {
    id: 'job-29',
    title: 'Solutions Architect',
    description: 'Design technical solutions for enterprise clients. Lead architecture discussions and provide technical guidance.',
    mustHaveSkills: ['architecture', 'cloud', 'aws'],
    niceToHaveSkills: ['kubernetes', 'microservices', 'terraform'],
    minYears: 7,
    location: 'New York, NY',
    isActive: true,
    createdAt: Date.now() - 2505600000,
    updatedAt: Date.now() - 2505600000,
  },
  {
    id: 'job-30',
    title: 'Performance Engineer',
    description: 'Optimize application performance and identify bottlenecks. Conduct load testing and implement monitoring.',
    mustHaveSkills: ['performance testing', 'monitoring', 'profiling'],
    niceToHaveSkills: ['java', 'python', 'grafana'],
    minYears: 3,
    location: 'Seattle, WA',
    isActive: true,
    createdAt: Date.now() - 2592000000,
    updatedAt: Date.now() - 2592000000,
  },
  {
    id: 'job-31',
    title: 'Integration Engineer',
    description: 'Build and maintain API integrations with third-party systems. Design data transformation pipelines.',
    mustHaveSkills: ['rest', 'api', 'javascript'],
    niceToHaveSkills: ['graphql', 'kafka', 'node'],
    minYears: 2,
    location: 'Remote',
    isActive: true,
    createdAt: Date.now() - 2678400000,
    updatedAt: Date.now() - 2678400000,
  },
  {
    id: 'job-32',
    title: 'Business Intelligence Analyst',
    description: 'Create dashboards and reports to support business decisions. Analyze data trends and provide insights.',
    mustHaveSkills: ['sql', 'tableau', 'analytics'],
    niceToHaveSkills: ['python', 'excel', 'powerbi'],
    minYears: 2,
    location: 'Chicago, IL',
    isActive: true,
    createdAt: Date.now() - 2764800000,
    updatedAt: Date.now() - 2764800000,
  },
  {
    id: 'job-33',
    title: 'Network Engineer',
    description: 'Design and maintain network infrastructure. Implement security policies and troubleshoot connectivity issues.',
    mustHaveSkills: ['networking', 'cisco', 'tcp/ip'],
    niceToHaveSkills: ['firewall', 'vpn', 'monitoring'],
    minYears: 4,
    location: 'Miami, FL',
    isActive: true,
    createdAt: Date.now() - 2851200000,
    updatedAt: Date.now() - 2851200000,
  },
  {
    id: 'job-34',
    title: 'Release Engineer',
    description: 'Manage release processes and deployment pipelines. Coordinate releases across multiple teams and environments.',
    mustHaveSkills: ['ci cd', 'jenkins', 'git'],
    niceToHaveSkills: ['docker', 'kubernetes', 'python'],
    minYears: 3,
    location: 'Austin, TX',
    isActive: true,
    createdAt: Date.now() - 2937600000,
    updatedAt: Date.now() - 2937600000,
  },
  {
    id: 'job-35',
    title: 'API Developer',
    description: 'Design and implement RESTful and GraphQL APIs. Write comprehensive API documentation and tests.',
    mustHaveSkills: ['rest', 'graphql', 'node'],
    niceToHaveSkills: ['typescript', 'docker', 'mongodb'],
    minYears: 2,
    location: 'Remote',
    isActive: true,
    createdAt: Date.now() - 3024000000,
    updatedAt: Date.now() - 3024000000,
  },
  {
    id: 'job-36',
    title: 'Embedded Systems Engineer',
    description: 'Develop firmware for IoT devices and embedded systems. Optimize for power consumption and memory usage.',
    mustHaveSkills: ['c', 'embedded', 'firmware'],
    niceToHaveSkills: ['c++', 'rtos', 'iot'],
    minYears: 4,
    location: 'San Jose, CA',
    isActive: true,
    createdAt: Date.now() - 3110400000,
    updatedAt: Date.now() - 3110400000,
  },
  {
    id: 'job-37',
    title: 'Computer Vision Engineer',
    description: 'Develop image processing and computer vision algorithms. Work with deep learning models for object detection.',
    mustHaveSkills: ['python', 'opencv', 'computer vision'],
    niceToHaveSkills: ['tensorflow', 'pytorch', 'cuda'],
    minYears: 3,
    location: 'Palo Alto, CA',
    isActive: true,
    createdAt: Date.now() - 3196800000,
    updatedAt: Date.now() - 3196800000,
  },
  {
    id: 'job-38',
    title: 'Automation Engineer',
    description: 'Automate business processes and workflows. Build RPA solutions and integrate systems.',
    mustHaveSkills: ['automation', 'python', 'scripting'],
    niceToHaveSkills: ['selenium', 'ansible', 'rest'],
    minYears: 2,
    location: 'Houston, TX',
    isActive: true,
    createdAt: Date.now() - 3283200000,
    updatedAt: Date.now() - 3283200000,
  },
  {
    id: 'job-39',
    title: 'React Developer',
    description: 'Build modern single-page applications using React. Implement state management and optimize rendering performance.',
    mustHaveSkills: ['react', 'javascript', 'html'],
    niceToHaveSkills: ['redux', 'typescript', 'webpack'],
    minYears: 2,
    location: 'Remote',
    isActive: true,
    createdAt: Date.now() - 3369600000,
    updatedAt: Date.now() - 3369600000,
  },
  {
    id: 'job-40',
    title: 'Backend Developer - PHP',
    description: 'Develop web applications using PHP and Laravel. Build RESTful APIs and optimize database queries.',
    mustHaveSkills: ['php', 'laravel', 'mysql'],
    niceToHaveSkills: ['redis', 'docker', 'rest'],
    minYears: 3,
    location: 'Orlando, FL',
    isActive: true,
    createdAt: Date.now() - 3456000000,
    updatedAt: Date.now() - 3456000000,
  },
  {
    id: 'job-41',
    title: 'Cloud Security Engineer',
    description: 'Implement security controls in cloud environments. Conduct security audits and respond to incidents.',
    mustHaveSkills: ['aws', 'security', 'compliance'],
    niceToHaveSkills: ['terraform', 'kubernetes', 'python'],
    minYears: 5,
    location: 'Washington, DC',
    isActive: true,
    createdAt: Date.now() - 3542400000,
    updatedAt: Date.now() - 3542400000,
  },
  {
    id: 'job-42',
    title: 'Frontend Engineer - Svelte',
    description: 'Build reactive web applications using Svelte. Focus on performance and minimal bundle sizes.',
    mustHaveSkills: ['svelte', 'javascript', 'html'],
    niceToHaveSkills: ['typescript', 'vite', 'tailwind'],
    minYears: 1,
    location: 'Remote',
    isActive: true,
    createdAt: Date.now() - 3628800000,
    updatedAt: Date.now() - 3628800000,
  },
  {
    id: 'job-43',
    title: 'Platform Engineer',
    description: 'Build internal developer platforms and tools. Improve developer experience and deployment workflows.',
    mustHaveSkills: ['kubernetes', 'docker', 'terraform'],
    niceToHaveSkills: ['golang', 'python', 'aws'],
    minYears: 4,
    location: 'San Francisco, CA',
    isActive: true,
    createdAt: Date.now() - 3715200000,
    updatedAt: Date.now() - 3715200000,
  },
  {
    id: 'job-44',
    title: 'ETL Developer',
    description: 'Design and implement data extraction, transformation, and loading processes. Optimize data pipelines.',
    mustHaveSkills: ['sql', 'etl', 'data engineering'],
    niceToHaveSkills: ['python', 'airflow', 'spark'],
    minYears: 3,
    location: 'Boston, MA',
    isActive: true,
    createdAt: Date.now() - 3801600000,
    updatedAt: Date.now() - 3801600000,
  },
  {
    id: 'job-45',
    title: 'Ruby on Rails Developer',
    description: 'Build web applications using Ruby on Rails. Implement MVC architecture and RESTful routing.',
    mustHaveSkills: ['ruby', 'rails', 'postgresql'],
    niceToHaveSkills: ['redis', 'sidekiq', 'rspec'],
    minYears: 3,
    location: 'Portland, OR',
    isActive: true,
    createdAt: Date.now() - 3888000000,
    updatedAt: Date.now() - 3888000000,
  },
];

export async function seedDatabase(
  addCandidate: (candidate: Candidate) => Promise<void>,
  addJob: (job: Job) => Promise<void>
): Promise<void> {
  for (const candidate of seedCandidates) {
    await addCandidate(candidate);
  }

  for (const job of seedJobs) {
    await addJob(job);
  }
}
